driver:
  name: vagrant
  provider: vmware_fusion
  customize:
    numvcpus: 4
    memsize: 4096

provisioner:
  require_chef_omnibus: true

platforms:
  - name: macos-10.9
    driver:
      box: sensu/macos-10.9
    attributes:
      omnibus_sensu:
        project_revision: feature/macos