<%
build_version = ENV["SENSU_VERSION"]
build_iteration = ENV["BUILD_NUMBER"]
gpg_passphrase = ENV["GPG_PASSPHRASE"]
gnupg_path = ENV["GNUPG_PATH"]
aws_ssh_key_id = ENV["AWS_SSH_KEY_ID"]
aws_ssh_key_path = ENV["AWS_SSH_KEY_PATH"]

if gpg_passphrase && gnupg_path
  # no-op
elsif gpg_passphrase || gnupg_path
  raise "Both GPG_PASSPHRASE and GNUPG_PATH must be set for signed RPMs"
end

unless build_version && build_iteration
  raise "SENSU_VERSION and BUILD_NUMBER must be set"
end
%>

driver:
  name: ec2
  instance_type: m3.medium
  iam_profile_name: sensu-omnibus-artifact-manager
  <% unless aws_ssh_key_id.nil? %>
  aws_ssh_key_id: <%= aws_ssh_key_id %>
  <% end %>
<% unless aws_ssh_key_path.nil? %>
transport:
  ssh_key: <%= aws_ssh_key_path %>
<% end %>

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.13.37

platforms:
  - name: centos-7
    run_list: yum-epel::default
  - name: centos-6
    run_list: yum-epel::default
  - name: centos-5.11
    run_list: yum-epel::default
  - name: centos-5.11-i386
    driver:
      instance_type: m1.medium
    run_list: yum-epel::default
  - name: debian-7
    run_list: apt::default
  - name: debian-7-i386
    driver:
      instance_type: m1.medium
    run_list: apt::default
  - name: debian-6
    run_list: apt::default
  - name: freebsd-11.0
    run_list:
      - omnibus_sensu::freebsd_portsnap
      - freebsd::pkgng
  - name: freebsd-10.3
    driver:
      user_data: "user-data/freebsd-10.sh"
    run_list:
      - omnibus_sensu::freebsd_portsnap
      - freebsd::pkgng
  - name: freebsd-9.3
    run_list:
      - freebsd::portsnap
      - freebsd::pkgng
  - name: ubuntu-16.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-12.04-i386
    driver:
      instance_type: m1.medium
    run_list: apt::default

suites:
  - name: default
    run_list:
    - omnibus_sensu::default
    attributes:
      omnibus_sensu:
        build_version: "<%= build_version %>"
        build_iteration: "<%= build_iteration %>"
        gpg_passphrase: "<%= gpg_passphrase %>"
