sudo: false
language: ruby
rvm: 2.3.0
bundler_args: "--without='vagrant'"
before_install:
- gem update --system
- gem --version
- gem install bundler --version 1.11.2
- openssl aes-256-cbc -K $encrypted_d8b89d758c52_key -iv $encrypted_d8b89d758c52_iv
  -in .travis/sensu-omnibus-artifact-builder.pem.enc -out .travis/sensu-omnibus-artifact-builder.pem
  -d
script: travis_retry ./build.sh
branches:
  only:
  - master
  - "/^v\\d.*\\.\\d.*\\.\\d.*-.*\\d$/"
matrix:
  allow_failures:
  - env: BUILD_PLATFORM=debian-8-i386
  - env: BUILD_PLATFORM=centos-7-i386
  - env: BUILD_PLATFORM=ubuntu-1604-i386
env:
  matrix:
  - BUILD_PLATFORM=debian-8
  - BUILD_PLATFORM=debian-8-i386
  - BUILD_PLATFORM=debian-7
  - BUILD_PLATFORM=debian-7-i386
  - BUILD_PLATFORM=ubuntu-1604
  - BUILD_PLATFORM=ubuntu-1604-i386
  - BUILD_PLATFORM=ubuntu-1404
  - BUILD_PLATFORM=ubuntu-1404-i386
  - BUILD_PLATFORM=ubuntu-1204
  - BUILD_PLATFORM=ubuntu-1204-i386
  - BUILD_PLATFORM=centos-7
  - BUILD_PLATFORM=centos-7-i386
  - BUILD_PLATFORM=centos-6
  - BUILD_PLATFORM=centos-6-i386
  - BUILD_PLATFORM=centos-5
  - BUILD_PLATFORM=centos-5-i386
  - BUILD_PLATFORM=freebsd-11
  - BUILD_PLATFORM=freebsd-10
  - BUILD_PLATFORM=freebsd-10-i386
  global:
  - AWS_REGION=us-west-2
  - AWS_S3_CACHE_BUCKET=sensu-omnibus-cache
  - AWS_S3_ARTIFACT_BUCKET=sensu-omnibus-artifacts
  - AWS_SSH_KEY_ID=sensu-omnibus-artifact-builder
  - AWS_SSH_KEY_PATH=.travis/sensu-omnibus-artifact-builder.pem
  - secure: b2j0L3FanQcjJNXtebkoHgk4P5EBc/5yPimFq3RcmNASIEOdtwR46fppe5tzYy0E5cgrgBpMfrRQnfPgZH0iHVG8h44N47D7R7ihSECTj5Ibl6gzu9rltYw7PjUHzyLyS1g/QkgRRmApJyYmoVKsjGl78AKnwHcEnGf/7SRpKS6o+K6fVoMNZujf/J12RWCuCSg902kUimAjA/DYSj0n3NebJ8AyV3WkXL4I81KbyVHKM5ymtNP5hsL5bDFNXXp0AEvHL8Cbp1YJlHZl2YQSj+hY6f3DGyL8zNOBAv2Ivppot8nOZBJvZoUt4ahCCxm5sy9e8gn8ijhSAqarNG2INuotwkAXzquBtejs+xz9OuosEC7RAlZXkuVK0y6RLF2DcxGDs1WV65RT948N/tRh9fGLo+nHNXi9I4GEG1laWRPCd6hmVwvxnDhp8lHYagN9f9ILp6+HEeU/9+sNoTz9pSL2s79tHF9xuxEh4FTyBbaVt4WOByrcW4J/dinb/XhDQ99ApQ+iUyJ2ABjfZwWjoGSkvWRK1AzYeViSSIfYtHPIsvaOCZZswA8AqR+Kb/GLm6/FcIhbWxJ6ynR13cVnzIKZne0IvJiVbWrrpGXTmz7HBNCP6yVKv1PzyKnOAbAp+7SEUBb3RNxRNp0M8rXdDYqDoQJAsDKJUeQ7B9B0VSE=
notifications:
  slack:
    secure: s58pj2JUq70OuzwA+/LUf0ZdVGc7vdeFb4WZrt0bzRhK1tcplKmYCzscXZBnKBHYjYI3jx3y4b+neUq7MmSMbNCdaA/DdCxD2XzBi+BMM7RzXYtid/IIDrIhLdTtQh9GcibUZLpz3XlZWNZSb9uK373uQlC0k6JM+WS57jPC2ssmgUmftN10QgldFx+AkzOmrfAaueMOcAQcH9cUkCQdDvvLZ+tBVQAv4SHuQXwmM5bjVFb5qTsUAXIiPtlFc2hNu0ruhOChggt2B/cgrA5kL1r3lhFY8I2Ugj6je+F/3LNAwpmf7YASgbC4lNP+BE/iIb2nazr2TZtT5XcYHEWqjMofvysgwc8ooeLhclrc075CIWtkljKjsZEr9jOsMPYeL2D1bu2Hrz0UE5vOW5oby7mpr1kj+m+R6MJPh57hC5mBU5XQJgPT7+CVBV52GrZSKTG7QHK0qK1iY8gStmc8U63kz3I+p+Htnzo8VnppGSClJwksKokqis4gC/hHTjJnZHGJgGYfyDYFgSSNj6ztTgt0n+LHdiTRFb8UmZp18wbWWJnN1W6vjJbS4r/+76CBMcdz5iaUHrgbMKIU+kgCOIQWUKjnjAq/u1CfS1gA/pES9JtiVDFPMcVIPTqI/p59tyYNUtvEEQJNzB5YsnK0/21VDZ9/dl7FjGZTaRCwPp0=
