sudo: false
language: ruby
rvm: 2.3.0
bundler_args: "--without='vagrant'"
before_install:
- gem update --system
- gem --version
- gem install bundler --version 1.11.2
- openssl aes-256-cbc -K $encrypted_d8b89d758c52_key -iv $encrypted_d8b89d758c52_iv
  -in .travis/sensu-omnibus-artifact-builder.pem.enc -out .travis/sensu-omnibus-artifact-builder.pem
  -d
script: "./build.sh"
branches:
  only:
  - master
  - "/^v\\d.*\\.\\d.*\\.\\d.*-.*\\d$/"
env:
  matrix:
  - BUILD_PLATFORM=debian-7
  - BUILD_PLATFORM=debian-7-i386
  - BUILD_PLATFORM=debian-6
  - BUILD_PLATFORM=ubuntu-1604
  - BUILD_PLATFORM=ubuntu-1404
  - BUILD_PLATFORM=ubuntu-1204
  - BUILD_PLATFORM=ubuntu-1204-i386
  - BUILD_PLATFORM=centos-7
  - BUILD_PLATFORM=centos-6
  - BUILD_PLATFORM=freebsd-11
  - BUILD_PLATFORM=freebsd-10
  - BUILD_PLATFORM=freebsd-9
  global:
  - AWS_REGION=us-west-2
  - AWS_S3_CACHE_BUCKET=sensu-omnibus-cache
  - AWS_S3_ARTIFACT_BUCKET=sensu-omnibus-artifacts
  - AWS_SSH_KEY_ID=sensu-omnibus-builder
  - AWS_SSH_KEY_PATH=.travis/sensu-omnibus-artifact-builder.pem
  - secure: i5BU8vTJvS4jUAupUyGj4ccAYcn3uk7HbcMNRWijeFQ/7OhOrfjtVdAHQHR+Pp43qNdffseMAgPnX4xeU4T3NWUUHY21FQ4DtIVyDwrQWLnZ4AGGYtAcsiCa4GrKO2UQvySotByJ7uNCNjGuRjzcwdb8ZsKgPiXbx3bvsoPiBKyEK5Nf7EYj1VItR4ENsI274pCl0eUffqAe99vEmMwbhCmVQagLQcP24DijUyOaN55BmsU+/n2zzOSwigk2V/OSlxsahGsCgKVsVOq7TYZUwFvlheyBa7/5r0Tr/Aoa9ORmN/Hdy1CLaMccIBrbsuWHGwb6CsWDMUuqoSvmqgjUGuhX0sPP/le8FWHw+Fi1AHEWJCqqml909kzo8jPRaSvxhylPeAuPuf7QCc0x/3E8hssioVd9PvS7Vv37g+vCPthkBi2mdpBt3y1SF+jAdzkeQtphEPKbJ8ShiwTx9l6H3ajY2Wjzva06mkSm59ZlnOLA+C8goCDWqftGitzzFVsRN6iECjs0tyj3yZpVLy2Is+C14nee7r9e3N0joiQIrVhKRwxZEGCXRofnqBlNOntMk3Op0AK7WsWfNxXK4YioD3vOpTM3yGOsGURvAGHznbBxq6sysdc5xAsyDueXQuvbomGIOsBzcg0gFoBI23X+atRndRdQ8S64rGydSuZYSp4=
