sudo: false
language: ruby
rvm: 2.3.0
bundler_args: "--without='vagrant'"
before_install:
- gem update --system
- gem --version
- gem install bundler --version 1.11.2
- "openssl aes-256-cbc -K $encrypted_d8b89d758c52_key -iv $encrypted_d8b89d758c52_iv -in .travis/sensu-omnibus-artifact-builder.pem.enc -out .travis/sensu-omnibus-artifact-builder.pem -d"
script: ./build.sh
branches:
  only:
  - master
  - "/^v\\d.*\\.\\d.*\\.\\d.*-.*\\d$/"
env:
  matrix:
  - BUILD_PLATFORM=debian-7
  - BUILD_PLATFORM=debian-7-i386
  - BUILD_PLATFORM=debian-6
  - BUILD_PLATFORM=ubuntu-1604
  - BUILD_PLATFORM=ubuntu-1404
  - BUILD_PLATFORM=ubuntu-1204
  - BUILD_PLATFORM=ubuntu-1204-i386
  - BUILD_PLATFORM=centos-7
  - BUILD_PLATFORM=centos-6
  - BUILD_PLATFORM=freebsd-11
  - BUILD_PLATFORM=freebsd-10
  - BUILD_PLATFORM=freebsd-9
  global:
  - AWS_REGION=us-west-2
  - AWS_S3_CACHE_BUCKET=sensu-omnibus-cache
  - AWS_S3_ARTIFACT_BUCKET=sensu-omnibus-artifacts
  - secure: DtnxUv18YOUX/dRAiKANrP9TsFbF2iSwPjGSu8pi9sa/kofwVFB7G9YUSxg9ot6MimoEDrvaQivpTWJVP8i7673TnNKaEwd8TZhXhMuBLs//9/GFk6xEoBJ8oO7U/JjilG6oReQgiwx5rwNV+sTU9nBMfuvvR3WGZ95o9MM4h+jlvzKesi2bSNUz0bxEyShU/DRNO7Ep6KPpFGB5thPPri8dq/1lXH4SnQOZHo/JOwsXqw28TwCaeI/V7mLe137fmlwICG+IQP6JcBpItK1p8LI4Knqb7PS1XibiIHIN3yfoTPpFQ+MMWzBXkLdZD6u6zqPc4vngDxnrHAQVMaKN9BqZrm/tCtueHEejDdFu6g/Ncwgpl7rpRUoT2ocL3ak5Zr3L7am4H1RXKE6Sky/WtwqdUk/KTk/5g7TwMMLsyxXes9/8Bq4SILWYWXCylczvyzNGJm/n9DTNjNhGtfQBdG7yHgtIdDo0/UBl11YRj5GekZHKwa56gf1HjyCNh+YDEXeprmeV9db1UfjV8oQ1sXE/V9FHqT69CcVcgvugZSpd8suiBuynObjjipVmPUXeOpe5BdWSTmc2TYk7/cSdONFw6omSWWOoTaK1ty98nSGLzGFMc6KKcwxkm1HP/fVxyhefWGnxEWEOpZYwC7ARwcIlemUh8HgR8+NtZX2K79w=
